import type { Metadata } from 'next';
import { mainFont, secondaryFont } from './shared/utils/fonts';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont} ${secondaryFont}`}>{children}</body>
    </html>
  );
}
